spring.application.name=UberLocationService

#mySQl
spring.datasource.url=jdbc:mysql://localhost:3306/uber_db_local
spring.datasource.username=root
spring.datasource.password=bhopal@123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

server.port=7777

spring.data.redis.host=localhost
spring.data.redis.port=6379